# Generated by Django 5.1.4 on 2026-04-29 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gafou', '0004_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='mode',
            name='type',
            field=models.CharField(choices=[('homme', 'Hommes'), ('femme', 'Femmes'), ('enfant', 'Enfants')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
