# Generated by Django 5.1.4 on 2026-04-30 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gafou', '0003_alter_product_created_at'),
        ('Gafou', '0005_mode_type'),
    ]

    operations = [
    ]
