# Generated by Django 5.1.4 on 2026-04-30 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gafou', '0006_merge_0003_alter_product_created_at_0005_mode_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beaute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_promo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image', models.ImageField(upload_to='beaute/')),
                ('type', models.CharField(choices=[('cosmetique', 'Cosmétiques'), ('soin', 'Soins')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
