# Generated by Django 5.1.4 on 2026-04-30 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gafou', '0007_beaute'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hygiene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('prix', models.FloatField()),
                ('prix_promo', models.FloatField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='hygiene/')),
                ('type', models.CharField(choices=[('corps', 'Corps'), ('sante', 'Santé')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
