# Generated by Django 6.0.5 on 2026-05-11 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gafou', '0009_product_image2_product_image3_product_image4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='beaute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Gafou.beaute'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='hygiene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Gafou.hygiene'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Gafou.mode'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Gafou.product'),
        ),
    ]
