# Generated by Django 6.0.5 on 2026-05-12 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gafou', '0011_boutique'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boutique',
            old_name='est_bloquee',
            new_name='is_blocked',
        ),
        migrations.RemoveField(
            model_name='boutique',
            name='proprietaire',
        ),
    ]
