# Generated by Django 6.0.5 on 2026-05-15 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gafou', '0012_rename_est_bloquee_boutique_is_blocked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
