# Generated by Django 6.0.5 on 2026-06-11 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gafou', '0016_favori'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favori',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='favori',
            name='hygiene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='Gafou.hygiene'),
        ),
        migrations.AddField(
            model_name='favori',
            name='mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='Gafou.mode'),
        ),
        migrations.AlterField(
            model_name='favori',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='Gafou.product'),
        ),
        migrations.AddConstraint(
            model_name='favori',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='unique_product_favori'),
        ),
        migrations.AddConstraint(
            model_name='favori',
            constraint=models.UniqueConstraint(fields=('user', 'mode'), name='unique_mode_favori'),
        ),
        migrations.AddConstraint(
            model_name='favori',
            constraint=models.UniqueConstraint(fields=('user', 'hygiene'), name='unique_hygiene_favori'),
        ),
    ]
