# Generated by Django 6.0.5 on 2026-06-11 03:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gafou', '0017_alter_favori_unique_together_favori_hygiene_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favori',
            name='unique_product_favori',
        ),
        migrations.RemoveConstraint(
            model_name='favori',
            name='unique_mode_favori',
        ),
        migrations.RemoveConstraint(
            model_name='favori',
            name='unique_hygiene_favori',
        ),
        migrations.AddConstraint(
            model_name='favori',
            constraint=models.UniqueConstraint(condition=models.Q(('product__isnull', False)), fields=('user', 'product'), name='unique_product_favori'),
        ),
        migrations.AddConstraint(
            model_name='favori',
            constraint=models.UniqueConstraint(condition=models.Q(('mode__isnull', False)), fields=('user', 'mode'), name='unique_mode_favori'),
        ),
        migrations.AddConstraint(
            model_name='favori',
            constraint=models.UniqueConstraint(condition=models.Q(('hygiene__isnull', False)), fields=('user', 'hygiene'), name='unique_hygiene_favori'),
        ),
    ]
