# Generated by Django 6.0.5 on 2026-06-11 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gafou', '0018_remove_favori_unique_product_favori_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='favori',
            name='beaute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='Gafou.beaute'),
        ),
    ]
