# Generated by Django 6.0.5 on 2026-06-11 03:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gafou', '0019_favori_beaute'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='favori',
            constraint=models.UniqueConstraint(condition=models.Q(('beaute__isnull', False)), fields=('user', 'beaute'), name='unique_beaute_favori'),
        ),
    ]
